Rename interactions to tasks
cucumber/screenplay.js pull request #34
Opened 2021-07-13 10:23 UTC by aslakhellesoy

# Description

Rename `Interaction` to `Task` in code and documentation.

# Motivation & context

The thing that an actor attempts to do is a *task*, not an *interaction*. See #31 for details. 

## Type of change

- Refactoring/debt (improvement to code design or tooling without changing behaviour)
- Breaking change (will cause existing functionality to not
  work as expected)

2021-07-19 18:57 UTC, mattwynne approved these changes

2021-07-20 07:45 UTC, vincent-psarga commented on features/support/tasks/dom/shout.ts
> +export const shout: Shout = (message) => {
Decomposition looks nice :)

2021-07-20 08:34 UTC, vincent-psarga approved these changes

2021-07-20 20:40 UTC, mattwynne commented on README.md
> +    | task |----------->| interaction |
I guess ideally it would show them both implementing/inheriting from `Action`

2021-08-02 12:25 UTC, aurelien-reeves requested changes
A CHANGELOG entry is missing.

2021-09-02 13:49 UTC, merged